# api 服务端口，可以改
server:
  port: 9082

spring:
  # ---------------- mysql 数据库配置，必须改 ----------------
  datasource:
    username: mysqlusername
    password: mysqlpassword
    url: jdbc:mysql://mysqlip:3306/databaseminimablog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis 配置，必须改
  redis:
    host: redisip
    password: redisassword
    port: 6379

  mail: # ---------------- 邮箱配置，必须改 ----------------
    default-encoding: UTF-8
    host: smtp.mxhichina.com   # <--------改这里 ----------------
    password: smtppassword  # <--------改这里 ----------------
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          starttls:
            enable: true
            required: true
    protocol: smtp
    username: admin@abc.cn   # <--------改这里 ----------------

# ---------------- 自定义环境变量，必须改 ----------------
env:
  # 网站名称
  site-name: 简笔记免费版
  # 后台打开的前台按钮地址；邮件中打开的网站
  admin-email: admin@abc.com
  # 邮件中打开的网站
  site-url: https://www.abc.com
  # gravatar 头像代理 url，（%md5% 不要改）
  avatar-url: https://cdn.sep.cc/avatar/%md5%?s=55
  # redis 统一 key 前缀
  redis-key-prefix: redis-minimablog-free
  # 服务器上静态文件路径
  path:
    static: /data/abc.com/static
  domain:
    # 管理后台域名
    user: 'https://user.abc.com'
    # api 接口域名
    api: 'https://api.abc.com'
    # 上传文件域名
    upload: 'https://upload.abc.com'
  ip-city:
    # 选择一个：cz88 或 baidu
    use-type: baidu
    # 百度的 ip 转城市查询接口的 access key
    baidu:
      access-key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    # 纯真ip库转换文件路径，参考：https://cz88.com/geo-public
    cz88:
      db-path:  # 例如路径： /code/ip-region-db/cz88_public_v4.czdb
      secret: ''  # 纯真ip库密钥
  word-check:
    url: ''
